# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PoalimDemoIos' do
  use_frameworks!

  pod "Apollo"

  target 'PoalimDemoIosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoalimDemoIosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
